### ISSUE TITLE
Get "d8: command not found" when running job on V8

### ISSUE THREAD

**Issue by kchapelier** [vhf/monomorphist#1]
I tried to execute a test on V8 5.7.512 to get familiar with the tool but the orchestrator returned an error potentially hinting at some server side issue.

```
2017-01-20T11:01:43.747Z job queued...
2017-01-20T11:01:44.175Z job zt2vrg4fuXX5h8MSS started running...
2017-01-20T11:01:45.672Z stderr:
/start.sh: line 13: d8: command not found
gzip: hydrogen.cfg: No such file or directory
gzip: code.asm: No such file or directory

--------
2017-01-20T11:01:45.676Z No hydrogen IR generated.
```

https://mono.morph.ist/ir/YbDs2PhRFMRkQzFE6

Tried a bit later on V8 master with the same result.

**Comment by vhf** [comment]
Thanks for the report! Something is definitely wrong, you're right. Here are the images I build with d8: https://hub.docker.com/r/dockervhf/d8/tags/ all the ones weighing less than 70MB most probably had some errors and need fixing.

The v8 team might have changed something in v8's build process, requiring changes from my side.

```
If you really want to run this, either run 
`python gypfiles/gyp_v8` explicitly by hand 
or set the environment variable GYP_CHROMIUM_NO_ACTION=0.
ERROR at the command-line "--args":1:80: Build argument has no effect.
v8_use_external_startup_data=false v8_enable_disassembler=true v8_object_print=true is_debug=true target_cpu="x64"
                                                                               ^---
The variable "v8_object_print" was set as a build argument
but never appeared in a declare_args() block in any buildfile.
To view all possible args, run "gn args --list <builddir>"
```

**Comment by kchapelier** [comment]
Thanks for the quick response! Indeed I don't get the d8 error with V8 5.7.433 (whose image file is 88MB) but the errors on hydrogen.cfg and code.asm appear to persist.

```
2017-01-20T11:48:53.621Z job queued...
2017-01-20T11:48:53.717Z job 5JYYB5Z2XSj9nLmFZ started running...
2017-01-20T11:48:55.173Z stdout:
Concurrent recompilation has been disabled for tracing.

--------
2017-01-20T11:48:55.177Z stderr:
gzip: hydrogen.cfg: No such file or directory
gzip: code.asm: No such file or directory

--------
2017-01-20T11:48:55.179Z No hydrogen IR generated.
```
https://mono.morph.ist/ir/XNW5N4o4J64MgzxL9

**Comment by vhf** [comment]
This is not an issue with my images. Unfortunately I cannot provide good informations about why and when this happens. From what I gathered through experiments, very simple codes - a few lines rarely executed - don't make d8 generated asm. It might be that the code not going through the optimizing compiler - crankshaft or turbofan - doesn't generate this assembly.

I'll ask around, I also want to know the answer. :)

**Comment by vhf** [comment]
I fixed the images, thanks again for the issue.

My hypothesis seems to be confirmed: code not going through the optimizing compiler (or not generating enough interesting compiling artefacts?) won't generate the output (either hydrogen IR or asm) necessary for IRHydra.

Here is a working example on the latest master: https://mono.morph.ist/ir/L2QK9BnWpMzdkz3Le

**Comment by kchapelier** [comment]
Thank you for the fix and explanations !
